# Generated by Django 5.2.13 on 2026-04-12 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField()),
                ('scope', models.CharField(choices=[('global', 'Global'), ('workspace', 'Workspace'), ('channel', 'Channel')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macro_definitions', to='channels.channel')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_macros', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='macro_definitions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['name', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('channel__isnull', True), ('scope', 'global'), ('workspace__isnull', True)), models.Q(('channel__isnull', True), ('scope', 'workspace'), ('workspace__isnull', False)), models.Q(('channel__isnull', False), ('scope', 'channel'), ('workspace__isnull', True)), _connector='OR'), name='macro_scope_matches_target'), models.UniqueConstraint(condition=models.Q(('channel__isnull', True), ('scope', 'global'), ('workspace__isnull', True)), fields=('name',), name='unique_global_macro_name'), models.UniqueConstraint(condition=models.Q(('channel__isnull', True), ('scope', 'workspace')), fields=('workspace', 'name'), name='unique_workspace_macro_name'), models.UniqueConstraint(condition=models.Q(('scope', 'channel'), ('workspace__isnull', True)), fields=('channel', 'name'), name='unique_channel_macro_name')],
            },
        ),
    ]
