output "alb_dns_name" {
  description = "DNS name of the public ALB."
  value       = module.alb.dns_name
}

output "backend_ecr_repository_url" {
  description = "Backend ECR repository URL."
  value       = module.ecr_backend.repository_url
}

output "backend_security_group_id" {
  description = "Security group attached to the ECS service."
  value       = module.ecs_service.security_group_id
}

output "database_endpoint" {
  description = "RDS endpoint hostname."
  value       = module.rds.endpoint
}

output "database_master_secret_arn" {
  description = "Secrets Manager ARN generated by RDS for the master user."
  value       = module.rds.master_user_secret_arn
}

output "application_secret_arns" {
  description = "Application secret ARNs managed outside of Terraform values."
  value       = module.secrets.secret_arns
}
